# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mail_window.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1032, 620)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.send_Email = QtWidgets.QPushButton(self.tab)
        self.send_Email.setObjectName("send_Email")
        self.gridLayout_2.addWidget(self.send_Email, 6, 3, 1, 1)
        self.extract_Email_recipients = QtWidgets.QPushButton(self.tab)
        self.extract_Email_recipients.setObjectName("extract_Email_recipients")
        self.gridLayout_2.addWidget(self.extract_Email_recipients, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.subject = QtWidgets.QLineEdit(self.tab)
        self.subject.setObjectName("subject")
        self.gridLayout_2.addWidget(self.subject, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 5, 0, 1, 1)
        self.recipients_Email = QtWidgets.QLineEdit(self.tab)
        self.recipients_Email.setObjectName("recipients_Email")
        self.gridLayout_2.addWidget(self.recipients_Email, 0, 1, 1, 1)
        self.attachment = QtWidgets.QToolButton(self.tab)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.attachment.setFont(font)
        self.attachment.setToolTip("")
        self.attachment.setToolTipDuration(1)
        self.attachment.setStatusTip("")
        self.attachment.setAutoFillBackground(True)
        self.attachment.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        self.attachment.setArrowType(QtCore.Qt.NoArrow)
        self.attachment.setObjectName("attachment")
        self.gridLayout_2.addWidget(self.attachment, 4, 1, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 1, 1, 1)
        self.message_Email = QtWidgets.QTextEdit(self.tab)
        self.message_Email.setObjectName("message_Email")
        self.gridLayout_2.addWidget(self.message_Email, 6, 0, 1, 2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout.setObjectName("gridLayout")
        self.show_all = QtWidgets.QCommandLinkButton(self.tab_2)
        self.show_all.setObjectName("show_all")
        self.gridLayout.addWidget(self.show_all, 1, 3, 1, 1)
        self.search = QtWidgets.QPushButton(self.tab_2)
        self.search.setObjectName("search")
        self.gridLayout.addWidget(self.search, 1, 2, 1, 1)
        self.update = QtWidgets.QCommandLinkButton(self.tab_2)
        self.update.setObjectName("update")
        self.gridLayout.addWidget(self.update, 0, 3, 1, 1)
        self.users_number = QtWidgets.QLineEdit(self.tab_2)
        self.users_number.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.users_number.setObjectName("users_number")
        self.gridLayout.addWidget(self.users_number, 1, 1, 2, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.folders_list = QtWidgets.QComboBox(self.tab_2)
        self.folders_list.addItem("Select")
        self.folders_list.addItem("INBOX")
        self.folders_list.addItem("SENT")
        self.folders_list.addItem("OUTBOX")
        self.folders_list.addItem("SPAM")
        self.folders_list.addItem("TRASH")
        self.folders_list.setCurrentText("")
        self.folders_list.setObjectName("folders_list")
        self.gridLayout.addWidget(self.folders_list, 1, 0, 2, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 1, 1, 1)
        self.tableView = QtWidgets.QTableView(self.tab_2)
        self.tableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.tableView, 4, 0, 1, 2)
        self.progressBar = QtWidgets.QProgressBar(self.tab_2)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 8, 0, 1, 2)
        self.read_button = QtWidgets.QPushButton(self.tab_2)
        self.read_button.setObjectName("read_button")
        self.gridLayout.addWidget(self.read_button, 4, 2, 1, 1)
        self.folder_stats = QtWidgets.QCommandLinkButton(self.tab_2)
        self.folder_stats.setObjectName("folder_stats")
        self.gridLayout.addWidget(self.folder_stats, 8, 3, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Recipients"))
        self.send_Email.setText(_translate("MainWindow", "SEND "))
        self.extract_Email_recipients.setText(_translate("MainWindow", "Extract"))
        self.label_2.setText(_translate("MainWindow", "Subject"))
        self.subject.setPlaceholderText(_translate("MainWindow", "Enter subject here"))
        self.label_3.setText(_translate("MainWindow", "Message"))
        self.recipients_Email.setPlaceholderText(_translate("MainWindow", "File Name (Egs: File_name.txt)"))
        self.attachment.setWhatsThis(_translate("MainWindow", "Attach Files"))
        self.attachment.setText(_translate("MainWindow", "Attachment"))
        self.message_Email.setPlaceholderText(_translate("MainWindow", "Type Your Message here"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "SEND"))
        self.show_all.setText(_translate("MainWindow", "SHOW ALL"))
        self.search.setText(_translate("MainWindow", "SEARCH"))
        self.update.setText(_translate("MainWindow", "UPDATE"))
        self.users_number.setPlaceholderText(_translate("MainWindow", "Enter name of mailer to search"))
        self.label_4.setText(_translate("MainWindow", "Select Folder"))
        self.read_button.setText(_translate("MainWindow", "READ"))
        self.folder_stats.setText(_translate("MainWindow", "SHOW FOLDERS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "SEARCH"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

